"""Typed models for metadata inspection, change plans, and results.

These Pydantic models are the contract shared across the desktop backend and
both bots. They are intentionally interface-agnostic (no FastAPI or bot types).
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pathlib import Path

from pydantic import BaseModel, Field

from core.exposure.models import ExposureMode, ResolvedExposure
from core.imaging.resolution_models import ResolutionPlan


class ImageFormat(str, Enum):
    """Image formats the engine recognises."""

    JPEG = "JPEG"
    HEIF = "HEIF"
    TIFF = "TIFF"
    PNG = "PNG"
    WEBP = "WEBP"
    UNKNOWN = "UNKNOWN"


class DateStrategy(str, Enum):
    """How the date/time fields should be handled in a change plan."""

    KEEP_ORIGINAL = "keep_original"
    SET_EXPLICIT = "set_explicit"


class GPSData(BaseModel):
    """Decimal GPS coordinates plus optional altitude and label."""

    latitude: float = Field(..., ge=-90.0, le=90.0)
    longitude: float = Field(..., ge=-180.0, le=180.0)
    altitude_m: float | None = Field(
        default=None, description="Altitude in metres; positive above sea level."
    )
    address_label: str | None = Field(
        default=None,
        max_length=512,
        description="Human-readable label; NOT written to EXIF, kept for audit/UI.",
    )


class MetadataSummary(BaseModel):
    """A read-only snapshot of the metadata currently present in an image."""

    image_format: ImageFormat
    width: int | None = None
    height: int | None = None
    make: str | None = None
    model: str | None = None
    lens_model: str | None = None
    focal_length: str | None = None
    f_number: str | None = None
    focal_length_35mm: str | None = None
    #: Shot-specific exposure fields, present only when actually recorded by the
    #: camera OR generated by an exposure profile (labelled elsewhere). Never
    #: inferred or defaulted at read time.
    iso: int | None = None
    exposure_time: str | None = None
    exposure_bias: str | None = None
    aperture_value: str | None = None
    shutter_speed_value: str | None = None
    flash: int | None = None
    exposure_program: int | None = None
    metering_mode: int | None = None
    white_balance: int | None = None
    exposure_mode: int | None = None
    scene_capture_type: int | None = None
    light_source: int | None = None
    exif_image_width: int | None = None
    exif_image_height: int | None = None
    software: str | None = None
    datetime_original: str | None = None
    create_date: str | None = None
    modify_date: str | None = None
    offset_time_original: str | None = None
    gps_latitude: float | None = None
    gps_longitude: float | None = None
    gps_altitude_m: float | None = None
    has_gps: bool = False
    #: Flat map of every raw tag we could decode, for the "inspect original" view.
    raw_tags: dict[str, str] = Field(default_factory=dict)


class ChangePlan(BaseModel):
    """A fully-specified, validated description of the changes to apply.

    A change plan is produced by :meth:`MetadataEngine.build_change_plan`,
    validated by :meth:`validate_change_plan`, and consumed by
    :meth:`apply_metadata`. It is the single source of truth for the review
    screen and the audit sidecar.
    """

    source_path: Path
    destination_path: Path
    original_summary: MetadataSummary | None = None

    # Device / camera identity
    preset_id: str | None = None
    lens_id: str | None = None
    make: str | None = None
    model: str | None = None
    lens_model: str | None = None
    #: Optical lens fields — only written when a preset actually supplies them.
    focal_length_mm: float | None = None
    focal_length_35mm: float | None = None
    f_number: float | None = None
    #: EXIF LensSpecification [minF, maxF, minFNum@minF, minFNum@maxF].
    lens_specification: list[float] | None = None
    #: True when ``lens_model`` is a generated generic fallback, not verified.
    lens_is_generic: bool = False
    #: Preserve the source file's existing lens fields (don't touch them).
    keep_original_lens: bool = False
    #: Remove lens fields from the exported copy.
    remove_lens: bool = False
    software: str | None = None

    #: Shot-specific exposure fields. Default is to keep whatever the source
    #: already had (untouched, via the base EXIF copy) — these are NEVER
    #: populated from a device preset. Only written when the user explicitly
    #: supplies them and sets ``set_exposure`` (legacy CUSTOM shortcut).
    set_exposure: bool = False
    photographic_sensitivity: int | None = Field(default=None, gt=0, description="ISO")
    exposure_time: float | None = Field(default=None, gt=0, description="Seconds, e.g. 1/121 s")
    exposure_bias: float | None = Field(default=None, ge=-10.0, le=10.0, description="EV stops")

    #: Exposure simulation configuration. ``exposure_mode`` selects preserve /
    #: fill-missing / override / custom; ``resolved_exposure`` is the concrete,
    #: provenance-tagged result computed by the engine and consumed by the
    #: writer, verifier, audit report, and UI preview. Values from a profile are
    #: ALWAYS labelled "Simulated exposure metadata" — never authentic.
    exposure_mode: ExposureMode = ExposureMode.PRESERVE
    exposure_profile_id: str | None = None
    resolved_exposure: ResolvedExposure | None = None

    #: Output-resolution transform (None = keep the source's exact dimensions).
    resolution: ResolutionPlan | None = None

    #: Output-format policy: force conversion of the source to JPEG on export
    #: (e.g. for broad Apple Photos EXIF visibility from a PNG source).
    convert_to_jpeg: bool = False

    # Date / time
    date_strategy: DateStrategy = DateStrategy.KEEP_ORIGINAL
    datetime_original: datetime | None = None
    create_date: datetime | None = None
    modify_date: datetime | None = None
    #: e.g. "+02:00" — written to OffsetTime* tags.
    utc_offset: str | None = None
    timezone_name: str | None = Field(
        default=None, description="IANA zone name for audit/UI; not an EXIF tag."
    )

    # Location
    gps: GPSData | None = None
    remove_gps: bool = False

    # Tag management
    tags_to_remove: list[str] = Field(default_factory=list)
    strip_all_metadata: bool = False

    # Audit
    write_audit_sidecar: bool = True

    model_config = {"arbitrary_types_allowed": True}


class FieldChange(BaseModel):
    """One row of the before/after review table."""

    field: str
    original: str | None = None
    new: str | None = None
    #: One of: "added", "changed", "removed", "preserved".
    status: str


class ChangeDiff(BaseModel):
    """The full before/after diff shown on the review screen."""

    rows: list[FieldChange] = Field(default_factory=list)


class FieldVerification(BaseModel):
    """One field's requested-vs-actual comparison after export."""

    field: str
    requested: str | None = None
    actual: str | None = None
    ok: bool = True
    #: Provenance of the field: preserved / simulated / custom / derived / lens.
    source: str | None = None


class MetadataVerification(BaseModel):
    """Result of reading the exported file back and checking it matches the plan."""

    ok: bool = True
    #: True if a lens was requested and its LensModel was actually written.
    lens_model_ok: bool = True
    #: True if all requested exposure fields round-tripped (required ones present).
    exposure_ok: bool = True
    lens_model_requested: str | None = None
    lens_model_actual: str | None = None
    #: True if the exported file's dimensions match the source (no implicit resize).
    dimensions_ok: bool = True
    fields: list[FieldVerification] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)


class ExportResult(BaseModel):
    """The outcome of a single apply/export operation."""

    source_path: Path
    destination_path: Path
    audit_sidecar_path: Path | None = None
    bytes_written: int = 0
    converted_to_jpeg: bool = False
    sha256: str | None = None
    warnings: list[str] = Field(default_factory=list)
    verification: MetadataVerification | None = None
    success: bool = True

    model_config = {"arbitrary_types_allowed": True}
